### ISSUE TITLE
Add new content section to index.html

### ISSUE THREAD

**Issue by mobyvb** [mobyvb/sandbox#28]
Add a new content section to index.html. 
The content section should contain a header and some sentences describing a digital assistant called "Pull Pal", which automatically reads issues in a Github repository and creates pull requests to resolve the issues.
On wide screens, the new section should take up 60% of the width and the old section should take up 40% of the width. On small screens, each section should take up 100% of the width

Files: index.html

**Comment by black-crowned-night-heron** [comment]
on it

**Comment by black-crowned-night-heron** [comment]
on it

**Comment by black-crowned-night-heron** [comment]
on it

**Comment by black-crowned-night-heron** [comment]
on it

**Comment by black-crowned-night-heron** [comment]
on it

**Comment by black-crowned-night-heron** [comment]
on it
